### ISSUE TITLE
refactor: Migrate to GitLab

### ISSUE THREAD

**Issue by brlin-tw** [brlin-tw/dot-bashrc.d#5]
GitLab is now my preferred project hosting provider, this repo will be kept as a mirror instead.

## Subtasks

* [ ] Create a project on GitLab
* [ ] Push current history to GitLab
* [ ] Setup repository mirroring on GitLab
* [ ] Update references in documentation
* [ ] Update references on GitHub project metadata
